# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d672acb92314544e4a579d8329d49507fe4feeb2c79048b6568e02f0c5dd70f36719c8dde90bfd91b42872907f6fd379c699ebdf3c6a70297902d2f886f7ffbb

test:
  secret_key_base: 001dc657bf9cc52e38a83063a8148b3775ee7342d2d7f85c478fe0af29e119df57a27d6a35245b6b152a8b1b11d3e670285cc187481b408c642824a86b4caba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
